[package]
name = "lisp_interpreter"
version = "0.1.0"
authors = ["Trevor <71519259+TPXS-Drexel@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
